### ISSUE TITLE
[discussion] what is it ? how to use it ? may need example

### ISSUE THREAD

**Issue by setop** [RyanBrewer317/SaberVM#1]
Hi,

From what I read, it seems SaberVM would allow to compile a functional programming language of my own devising to something executable (native or with an interpreter) provided I write some front-end compiler that would translate this language to Saber opcodes/bytecodes/AST.

If so, is there any example of such language (an its associated front-end compiler) to illustrate how it should work ?

Else, I don't exactly see the point of having only the bottom half of the process. But maybe all of it is beyond my understanding, I don't know ...

Regards

**Comment by RyanBrewer317** [comment]
Good question. This project is still in active development and isn't usable quite yet. I hope to get a working implementation done sometime in February, if you want a rough timescale.

When it becomes usable, I'll have much more information here on how to use it.

In general you're completely right, you'd be expected to write your own frontend compiler that produces SaberVM bytecode. I'll have some documentation on how to get a basic little functional language to produce SaberVM bytecode, as well as how to compile a variety of interesting language features.

Having the bottom half of the process will still be useful, as SaberVM will take care of many of the final steps of compilation, such as supporting multiple platforms. LLVM fills a similar role for imperative languages, though with more optimizations.

Languages that target the BEAM VM, like Erlang and Elixir, have the option to target the BEAM's bytecode directly, target Erlang, or target something in between called Core Erlang. This is essentially just picking how early in the compilation process you want to hand it over to Erlang/BEAM. SaberVM has the same thing planned, with a Saber language you can target that is higher level and performs more transformations and optimizations. But note that a first version of that project will take a couple extra months at minimum.
